name: Build & Test

on: [pull_request, push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
    container:
      image: ubuntu:18.04
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: |
          apt-get update
          apt-get install -y wget curl make zip git gcc software-properties-common cmake g++ openjdk-8-jdk jq
          apt-get clean
      - name: install python 3.10
          apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
          wget https://www.python.org/ftp/python/3.10.14/Python-3.10.14.tgz
          tar -xvf Python-3.10.14.tgz
          cd Python-3.10.14 && ./configure --enable-optimizations --with-ensurepip=install --enable-shared --prefix=/usr/local LDFLAGS="-Wl,--rpath=/usr/local/lib" && make -j 4 && make install
      - name: build
        run: |
          pip3 install -r requirements.txt
          make dist
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: perfspect
          path: dist/perfspect*.tgz
